# Path: Alphintra/src/backend/auth-service/src/main/resources/application.yml
# Purpose: Configures Spring Boot for auth-service, aligning with docker-compose.minimal.yml

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/alphintra-auth-service}
    username: ${POSTGRES_USER:alphintra}
    password: ${POSTGRES_PASSWORD:alphintra123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/alphintra-auth-service}
    user: ${POSTGRES_USER:alphintra}
    password: ${POSTGRES_PASSWORD:alphintra123}

jwt:
  secret: ${JWT_SECRET:your-secure-jwt-secret}
  expiration: 86400000 # 24 hours in milliseconds

kyc:
  provider:
    name: placeholder
    api-key: ${KYC_API_KEY:}
    endpoint: ${KYC_ENDPOINT:}
    enabled: false

server:
  port: 8009