spring:
  # datasource:
  #   url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/alphintra_auth_service?user=alphintra&password=alphintra123}
  #   username: ${POSTGRES_USER:alphintra}
  #   password: ${POSTGRES_PASSWORD:alphintra123}
  
  datasource:
    url: jdbc:postgresql://postgres:5432/alphintra_auth_service
    username: alphintra
    password: alphintra123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


jwt:
  secret: ${JWT_SECRET:your-secure-jwt-secret}
  expiration: 86400000 # 24 hours in milliseconds

kyc:
  provider:
    name: placeholder
    api-key: ${KYC_API_KEY:}
    endpoint: ${KYC_ENDPOINT:}
    enabled: false

server:
  port: 8009