spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:alphintra_auth_service}
    username: ${DB_USERNAME:alphintra}
    password: ${DB_PASSWORD:alphintra123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    connect-retries: 10
  sql:
    init:
      mode: never
  main:
    banner-mode: off
  profiles:
    default: local

logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: ERROR
    com.alphintra.auth_service: INFO

jwt:
  secret: ${JWT_SECRET:U29tZVZlcnlTdHJvbmdTZWNyZXRLZXlXaXRoRW5vdWdoQnl0ZXNGb3JFUjUxMkFsZ29yaXRobS0xMjM0NTY3ODkwYWJjZGVmZ2hpams=}
  expiration: ${JWT_EXPIRATION:86400000}

kyc:
  provider:
    name: placeholder
    api-key: ${KYC_API_KEY:}
    endpoint: ${KYC_ENDPOINT:}
    enabled: false

stripe:
  api-key: ${STRIPE_API_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
  price-ids:
    basic: ${STRIPE_PRICE_ID_BASIC:price_basic}
    pro: ${STRIPE_PRICE_ID_PRO:price_pro}
    enterprise: ${STRIPE_PRICE_ID_ENTERPRISE:price_enterprise}
  success-url: ${STRIPE_SUCCESS_URL:http://localhost:3000/subscription/success}
  cancel-url: ${STRIPE_CANCEL_URL:http://localhost:3000/subscription/cancel}

server:
  port: ${SERVER_PORT:8009}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
