# Path: Alphintra/src/backend/auth-service/src/main/resources/application.yml
# Purpose: Configures Spring Boot, including database, Flyway, JWT, and KYC provider placeholders.

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/alphintra_auth_service
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

jwt:
  secret: ${JWT_SECRET:your-secure-jwt-secret}
  expiration: 86400000 # 24 hours in milliseconds

kyc:
  provider:
    name: placeholder
    api-key: ${KYC_API_KEY:}
    endpoint: ${KYC_ENDPOINT:}
    enabled: false

server:
  port: 8080