apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-gateway-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alphintra/platform.git
    targetRevision: main
    path: infra/kubernetes/environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
