apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-support-service
  namespace: alphintra
spec:
  template:
    spec:
      containers:
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
          args:
            - "--structured-logs"
            - "--port=5432"
            - "--address=127.0.0.1"
            - "--private-ip"
            - "--credentials-file=/secrets/cloudsql/service-account.json"
            - "alphintra-472817:us-central1:alphintra-db-instance"
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: cloudsql-sa
              mountPath: /secrets/cloudsql
              readOnly: true
      volumes:
        - name: cloudsql-sa
          secret:
            secretName: cloudsql-sa-secret
