apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-support-service
  namespace: alphintra
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: customer-support-service
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: LOG_LEVEL
              value: DEBUG
