global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'alphintra'
    replica: 'prometheus-1'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    metrics_path: /metrics
    scrape_interval: 15s

  # Spring Boot Gateway
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8080']
    metrics_path: /actuator/prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']

  # Auth Service
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8001']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Trading API
  - job_name: 'trading-api'
    static_configs:
      - targets: ['trading-api:8002']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Strategy Engine
  - job_name: 'strategy-engine'
    static_configs:
      - targets: ['strategy-engine:8003']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Broker Connector
  - job_name: 'broker-connector'
    static_configs:
      - targets: ['broker-connector:8005']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Broker Simulator
  - job_name: 'broker-simulator'
    static_configs:
      - targets: ['broker-simulator:8006']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # MLflow
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:5000']
    metrics_path: /metrics
    scrape_interval: 30s
    scrape_timeout: 10s

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # TimescaleDB
  - job_name: 'timescaledb'
    static_configs:
      - targets: ['timescaledb:5432']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Kafka
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # Node Exporter (if added later)
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']
  #   scrape_interval: 15s

  # cAdvisor (if added later)
  # - job_name: 'cadvisor'
  #   static_configs:
  #     - targets: ['cadvisor:8080']
  #   scrape_interval: 15s

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "http://cortex:9009/api/prom/push"
#     queue_config:
#       max_samples_per_send: 1000
#       max_shards: 200
#       capacity: 2500

# Remote read configuration
# remote_read:
#   - url: "http://cortex:9009/api/prom/read"
#     read_recent: true