version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/src/backend/auth-service"
    schedule:
      interval: "weekly"
  - package-ecosystem: "maven"
    directory: "/src/backend/service-gateway"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/mobile"
    schedule:
      interval: "weekly"
