apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-gateway
  labels:
    app: service-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-gateway
  template:
    metadata:
      labels:
        app: service-gateway
    spec:
      serviceAccountName: service-gateway
      containers:
        - name: service-gateway
          image: us-central1-docker.pkg.dev/alphintra-472817/alphintra/service-gateway:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: service-gateway-config
            - secretRef:
                name: service-gateway-secrets
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: SERVER_PORT
              value: "8080"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: service-gateway-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-gateway-config
                  key: REDIS_PORT
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 10
            periodSeconds: 10
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
