apiVersion: v1
kind: Service
metadata:
  name: service-gateway
  labels:
    app: service-gateway
spec:
  selector:
    app: service-gateway
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
