apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alphintra
resources:
  - no-code-service
patches:
  - path: patches/no-code-deployment.yaml
  - path: patches/no-code-cloudsql.yaml
  - path: patches/no-code-serviceaccount.yaml
images:
  - name: gcr.io/alphintra-472817/no-code-service
    newTag: latest
configMapGenerator:
  - name: no-code-service-config
    behavior: merge
    literals:
      - log-level=INFO
      - dev-mode=false
      - prometheus-enabled=true
      - cors-allow-origins=http://localhost:3000,https://dev.alphintra.internal
      - auth-service-url=http://auth-service.alphintra.svc.cluster.local:8009
      - aiml-service-url=http://ai-ml-strategy-service.alphintra.svc.cluster.local:8002
      - redis-url=
