apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ai-ml-strategy-service
  labels:
    app: ai-ml-strategy-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ai-ml-strategy-service
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
