apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - hpa.yaml
  - pdb.yaml

labels:
  - pairs:
      app: ai-ml-strategy-service
      component: backend
      tier: service

namespace: alphintra
