apiVersion: v1
kind: Service
metadata:
  name: ai-ml-strategy-service
  labels:
    app: ai-ml-strategy-service
    component: backend
    tier: service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8002"
    prometheus.io/path: "/health"
spec:
  type: ClusterIP
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: ai-ml-strategy-service
  sessionAffinity: None
