apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: alphintra-dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: auth-service
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes,dev"
        - name: LOGGING_LEVEL_ROOT
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_ALPHINTRA
          value: "DEBUG"
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
          value: "DEBUG"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,metrics,prometheus,env,configprops"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "true"
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "1.0"
        - name: SPRING_SLEUTH_ZIPKIN_BASE_URL
          value: "http://jaeger-collector.istio-system:14268"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
          value: "true"
        - name: JWT_EXPIRATION
          value: "3600000"
        - name: REFRESH_TOKEN_EXPIRATION
          value: "86400000"
        - name: PASSWORD_RESET_TOKEN_EXPIRATION
          value: "1800000"
        - name: ACCOUNT_VERIFICATION_ENABLED
          value: "false"
        - name: EMAIL_VERIFICATION_ENABLED
          value: "false"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 20
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3