apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: alphintra

resources:
  - namespace.yaml
  - no-code-service.yaml
  - no-code-service-db-secret.yaml
  - no-code-service-serviceaccount.yaml

labels:
  - pairs:
      environment: development
      tier: application

patches:
  - path: no-code-service-cloudsql-patch.yaml
    target:
      kind: Deployment
      name: no-code-service

replicas:
  - name: no-code-service
    count: 1