apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-code-service
  namespace: alphintra
spec:
  template:
    spec:
      serviceAccountName: no-code-service
      containers:
      - name: no-code-service
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: no-code-service-db
              key: DATABASE_URL
        ports:
        - name: http
          containerPort: 8006
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
        args:
          - "--port=5432"
          - "--address=0.0.0.0"
          - "--private-ip"
          - "alphintra-472817:us-central1:alphintra-db-instance"
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 128Mi
        ports:
        - containerPort: 5432
          name: cloudsql
        livenessProbe:
          tcpSocket:
            port: cloudsql
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: cloudsql
          initialDelaySeconds: 5
          periodSeconds: 5
