# Dev overlay manifests for no-code-service using the built image and app entrypoint
---
apiVersion: v1
kind: Service
metadata:
  name: no-code-service
  namespace: alphintra
  labels:
    app: no-code-service
    service: no-code-service
spec:
  type: ClusterIP
  selector:
    app: no-code-service
  ports:
    - name: http
      port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-code-service
  namespace: alphintra
  labels:
    app: no-code-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: no-code-service
      version: v1
  template:
    metadata:
      labels:
        app: no-code-service
        version: v1
    spec:
      # ServiceAccount is set via patch to enable Cloud SQL proxy auth
      containers:
        - name: no-code-service
          # This image will be updated by the CI job to the freshly built tag
          image: gcr.io/alphintra-prod/no-code-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8006
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8006
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8006
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 20m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REDIS_URL
              value: "redis://:redis123@redis:6379"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: BACKTEST_SERVICE_URL
              value: "http://backtest-service:8007"
            - name: PYTHONPATH
              value: "/app"
      # DATABASE_URL env and Cloud SQL proxy sidecar are injected via no-code-service-cloudsql-patch.yaml