apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-engine
  namespace: alphintra-dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/actuator/prometheus"
spec:
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
      - name: strategy-engine
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes,dev"
        - name: LOGGING_LEVEL_ROOT
          value: "DEBUG"
        - name: LOGGING_LEVEL_COM_ALPHINTRA
          value: "DEBUG"
        - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA
          value: "DEBUG"
        - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
          value: "health,info,metrics,prometheus,env,configprops,kafka"
        - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS
          value: "always"
        - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
          value: "true"
        - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
          value: "1.0"
        - name: SPRING_SLEUTH_ZIPKIN_BASE_URL
          value: "http://jaeger-collector.istio-system:14268"
        - name: SPRING_JPA_SHOW_SQL
          value: "true"
        - name: SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL
          value: "true"
        - name: STRATEGY_EXECUTION_MODE
          value: "SIMULATION"
        - name: ML_MODEL_REFRESH_INTERVAL
          value: "300"
        - name: FEATURE_CALCULATION_INTERVAL
          value: "60"
        - name: SIGNAL_GENERATION_ENABLED
          value: "true"
        - name: BACKTESTING_ENABLED
          value: "true"
        - name: PAPER_TRADING_ENABLED
          value: "true"
        - name: LIVE_TRADING_ENABLED
          value: "false"
        - name: RISK_MANAGEMENT_STRICT
          value: "false"
        - name: MAX_POSITION_SIZE
          value: "100000"
        - name: MAX_DAILY_TRADES
          value: "1000"
        - name: STOP_LOSS_PERCENTAGE
          value: "0.02"
        - name: TAKE_PROFIT_PERCENTAGE
          value: "0.05"
        - name: KAFKA_CONSUMER_GROUP_ID
          value: "strategy-engine-dev"
        - name: KAFKA_AUTO_OFFSET_RESET
          value: "earliest"
        - name: PYTHON_ML_SERVICE_URL
          value: "http://ml-service:8000"
        - name: FEATURE_STORE_BUCKET
          value: "features"
        - name: MODEL_REGISTRY_BUCKET
          value: "models"
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3