apiVersion: v1
kind: Service
metadata:
  name: wallet-service
  labels:
    app: wallet-service
    component: backend
    environment: dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8011"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8011
    targetPort: http
    protocol: TCP
  selector:
    app: wallet-service