package com.alphintra.trading_engine.strategy;

/**
 * Represents a trading decision signal generated by a strategy.
 * This enum defines the possible actions a trading bot can take.
 */
public enum Signal {
    /**
     * Indicates a decision to buy the base asset (e.g., ETC in ETC/USDT).
     */
    BUY,

    /**
     * Indicates a decision to sell the base asset.
     */
    SELL,

    /**
     * Indicates a decision to take no action and wait.
     */
    HOLD
}