apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: alphintra-dev
  labels:
    app: auth-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
      version: v1
  template:
    metadata:
      labels:
        app: auth-service
        version: v1
    spec:
      containers:
      - name: auth-service
        image: localhost:5001/alphintra/auth-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres.default.svc.cluster.local:5432/alphintra_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "alphintra"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: REDIS_HOST
          value: "redis-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secret
              key: jwt-secret
        - name: JWT_EXPIRATION
          value: "86400000"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.default.svc.cluster.local:9092"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: alphintra-dev
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: alphintra-dev
type: Opaque
data:
  jwt-secret: YWxwaGludHJhLWp3dC1zZWNyZXQtZm9yLWxvY2FsLWRldmVsb3BtZW50LW9ubHk= # alphintra-jwt-secret-for-local-development-only
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: alphintra-dev
type: Opaque
data:
  password: cGFzc3dvcmQxMjM= # password123