apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-simulator
  namespace: alphintra
  labels:
    app: broker-simulator
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broker-simulator
      version: v1
  template:
    metadata:
      labels:
        app: broker-simulator
        version: v1
    spec:
      containers:
      - name: broker-simulator
        image: k3d-alphintra-registry:5000/alphintra/broker-simulator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://timescaledb.default.svc.cluster.local:5432/timeseries_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "alphintra"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb-secret
              key: password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: REDIS_HOST
          value: "redis-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.default.svc.cluster.local:9092"
        - name: TRADING_API_URL
          value: "http://trading-api:8080"
        - name: MARKET_DATA_TOPIC
          value: "market-data"
        - name: ORDER_EVENTS_TOPIC
          value: "order-events"
        - name: TRADE_EVENTS_TOPIC
          value: "trade-events"
        - name: EXECUTION_EVENTS_TOPIC
          value: "execution-events"
        - name: MARKET_DATA_SIMULATION_ENABLED
          value: "true"
        - name: MARKET_DATA_SIMULATION_INTERVAL
          value: "1000"
        - name: ORDER_EXECUTION_DELAY_MS
          value: "100"
        - name: SLIPPAGE_FACTOR
          value: "0.001"
        - name: COMMISSION_RATE
          value: "0.001"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: broker-simulator
  namespace: alphintra
  labels:
    app: broker-simulator
spec:
  selector:
    app: broker-simulator
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP