# GraphQL Gateway Deployment for Unified API Layer
# Provides single GraphQL endpoint federating all microservices

apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-gateway-config
  namespace: alphintra
data:
  requirements.txt: |
    fastapi==0.104.1
    uvicorn[standard]==0.24.0
    strawberry-graphql[fastapi]==0.219.0
    httpx==0.25.2
    redis==5.0.1
    prometheus-fastapi-instrumentator==6.1.0
    pydantic==2.5.0
    python-multipart==0.0.6

---
apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
  namespace: alphintra
  labels:
    app: graphql-gateway
    service: graphql-gateway
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: graphql-gateway

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  namespace: alphintra
  labels:
    app: graphql-gateway
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphql-gateway
      version: v1
  template:
    metadata:
      labels:
        app: graphql-gateway
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: default
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
      - name: graphql-gateway
        image: python:3.11-slim
        imagePullPolicy: IfNotPresent
        command:
          - python
          - main.py
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        # Service URLs for microservice federation
        - name: TRADING_SERVICE_URL
          value: "http://trading-service.alphintra.svc.cluster.local:8080"
        - name: RISK_SERVICE_URL
          value: "http://risk-service.alphintra.svc.cluster.local:8080"
        - name: USER_SERVICE_URL
          value: "http://user-service.alphintra.svc.cluster.local:8080"
        - name: NO_CODE_SERVICE_URL
          value: "http://no-code-service.alphintra.svc.cluster.local:8080"
        - name: STRATEGY_SERVICE_URL
          value: "http://strategy-service.alphintra.svc.cluster.local:8080"
        - name: BROKER_SERVICE_URL
          value: "http://broker-service.alphintra.svc.cluster.local:8080"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service.alphintra.svc.cluster.local:8080"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service.alphintra.svc.cluster.local:8080"
        - name: REDIS_URL
          value: "redis://:alphintra_redis_pass@redis-primary.alphintra.svc.cluster.local:6379/7"
        - name: PYTHONPATH
          value: "/app"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: app-code
          mountPath: /app
        - name: tmp-volume
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
              - ALL
      volumes:
      - name: app-code
        configMap:
          name: graphql-gateway-code
      - name: tmp-volume
        emptyDir: {}
      initContainers:
      - name: wait-for-dependencies
        image: busybox:1.35
        command:
          - sh
          - -c
          - |
            echo "Waiting for Redis..."
            until nc -z redis-primary.alphintra.svc.cluster.local 6379; do
              echo "Waiting for Redis..."
              sleep 5
            done
            echo "Waiting for core services..."
            until nc -z trading-service.alphintra.svc.cluster.local 8080; do
              echo "Waiting for Trading Service..."
              sleep 5
            done
            echo "All dependencies are ready!"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - graphql-gateway
              topologyKey: kubernetes.io/hostname

---
# HorizontalPodAutoscaler for GraphQL Gateway
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: graphql-gateway-hpa
  namespace: alphintra
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: graphql-gateway
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60