apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Cloud Build Local Optimized Deployment with Google Distroless + Alpine Images
resources:
  - namespace.yaml
  - api-gateway.yaml
  - auth-service.yaml
  - eureka-server.yaml
  - config-server.yaml
  - postgresql-statefulset-optimized.yaml
  - redis-statefulset-optimized.yaml
  - graphql-gateway.yaml
  - trading-api-deployment.yaml
  - strategy-engine-deployment.yaml
  - broker-simulator-deployment.yaml
  - no-code-service.yaml
  - monitoring-stack.yaml

# Use Cloud Build Local images with correct tags
images:
  - name: k3d-alphintra-registry:5000/alphintra/api-gateway:latest
    newName: localhost:5001/alphintra/api-gateway
    newTag: distroless
  - name: k3d-alphintra-registry:5000/alphintra/auth-service:latest
    newName: localhost:5001/alphintra/auth-service
    newTag: distroless
  - name: k3d-alphintra-registry:5000/alphintra/trading-api:latest
    newName: localhost:5001/alphintra/trading-api
    newTag: optimized
  - name: k3d-alphintra-registry:5000/alphintra/graphql-gateway:latest
    newName: localhost:5001/alphintra/graphql-gateway
    newTag: optimized
  - name: k3d-alphintra-registry:5000/alphintra/strategy-engine:latest
    newName: localhost:5001/alphintra/strategy-engine
    newTag: optimized

# Resource optimization patches
patchesStrategicMerge:
  - patches/resource-optimization.yaml
  - patches/cloud-build-local-optimization.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: alphintra
    app.kubernetes.io/managed-by: kustomize
    deployment.version: cloud-build-local
    deployment.profile: distroless-alpine
    build.source: cloud-build-local
