# Optimized Redis StatefulSet for K3D with reduced resource usage
# Production-ready configuration optimized for Alpine Linux deployment

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: alphintra
data:
  redis.conf: |
    # Redis configuration optimized for K3D cluster with reduced resources
    
    # Network configuration
    bind 0.0.0.0
    port 6379
    tcp-backlog 128
    timeout 0
    tcp-keepalive 300
    
    # General configuration
    daemonize no
    supervised no
    pidfile /var/run/redis_6379.pid
    loglevel notice
    logfile ""
    databases 16
    
    # Memory optimization for K3D
    maxmemory 64mb
    maxmemory-policy allkeys-lru
    maxmemory-samples 3
    
    # Persistence configuration (optimized for K3D)
    save 900 1
    save 300 10
    save 60 10000
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir ./
    
    # AOF configuration (disabled for performance in K3D)
    appendonly no
    
    # Slow log configuration
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    
    # Client configuration
    maxclients 100
    
    # Security configuration
    requirepass changeme
    
    # Performance tuning for K3D
    tcp-keepalive 60
    timeout 0
    hz 10
    
    # Memory management
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    
    # HyperLogLog configuration
    hll-sparse-max-bytes 3000
    
    # Streams configuration
    stream-node-max-bytes 4096
    stream-node-max-entries 100
    
    # Active rehashing
    activerehashing yes
    
    # Client output buffer limits
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit replica 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    
    # Client query buffer limit
    client-query-buffer-limit 1gb
    
    # Protocol max buffer size
    proto-max-bulk-len 512mb
    
    # Lua script timeout
    lua-time-limit 5000
    
    # Cluster configuration (disabled for single instance)
    # cluster-enabled no
    
    # Latency monitor
    latency-monitor-threshold 100
    
    # Notify configuration
    notify-keyspace-events ""
    
    # Advanced configuration
    always-show-logo no
    
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: alphintra
  labels:
    app: redis
    component: cache
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: cache
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        imagePullPolicy: IfNotPresent
        command:
        - redis-server
        - /etc/redis/redis.conf
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: alphintra-secrets
              key: redis-password
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 10
        securityContext:
          runAsUser: 999
          runAsGroup: 999
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf
      securityContext:
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: alphintra
  labels:
    app: redis
    component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis

---
apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  namespace: alphintra
  labels:
    app: redis
    component: cache
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: redis