# Redis StatefulSet for K3D Internal Networking
# Provides caching, session management, and real-time data with ClusterIP service

apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: alphintra
data:
  redis.conf: |
    # Redis configuration optimized for financial trading platform
    bind 0.0.0.0
    port 6379
    protected-mode no
    
    # Memory management
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    
    # Persistence settings
    save 900 1
    save 300 10
    save 60 10000
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /data
    
    # Append only file
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    
    # Logging
    loglevel notice
    logfile /var/log/redis/redis-server.log
    
    # Network settings
    tcp-keepalive 300
    tcp-backlog 511
    timeout 0
    
    # Database settings
    databases 16
    
    # Security
    requirepass alphintra_redis_pass
    
    # Performance tuning
    hz 10
    dynamic-hz yes
    
    # Pub/Sub settings for real-time updates
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: alphintra
type: Opaque
data:
  # Base64 encoded: alphintra_redis_pass
  redis-password: YWxwaGludHJhX3JlZGlzX3Bhc3M=

---
apiVersion: v1
kind: Service
metadata:
  name: redis-primary
  namespace: alphintra
  labels:
    app: redis
    role: primary
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
    role: primary

---
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: alphintra
  labels:
    app: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: alphintra
  labels:
    app: redis
spec:
  serviceName: redis-headless
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: primary
    spec:
      securityContext:
        fsGroup: 1001
      containers:
      - name: redis
        image: redis:7-alpine
        imagePullPolicy: IfNotPresent
        command:
          - redis-server
          - /etc/redis/redis.conf
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        ports:
        - name: redis
          containerPort: 6379
          protocol: TCP
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        - name: redis-config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
        - name: redis-logs
          mountPath: /var/log/redis
      volumes:
      - name: redis-config
        configMap:
          name: redis-config
      - name: redis-logs
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "local-path"
      resources:
        requests:
          storage: 5Gi