apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-engine
  namespace: alphintra-dev
  labels:
    app: strategy-engine
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strategy-engine
      version: v1
  template:
    metadata:
      labels:
        app: strategy-engine
        version: v1
    spec:
      containers:
      - name: strategy-engine
        image: localhost:5001/alphintra/strategy-engine:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "kubernetes"
        - name: SERVER_PORT
          value: "8080"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://timescaledb.default.svc.cluster.local:5432/timeseries_db"
        - name: SPRING_DATASOURCE_USERNAME
          value: "alphintra"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: timescaledb-secret
              key: password
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        - name: SPRING_JPA_DATABASE_PLATFORM
          value: "org.hibernate.dialect.PostgreSQLDialect"
        - name: REDIS_HOST
          value: "redis-master.default.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka.default.svc.cluster.local:9092"
        - name: TRADING_API_URL
          value: "http://trading-api:8080"
        - name: BROKER_SIMULATOR_URL
          value: "http://broker-simulator:8080"
        - name: MLFLOW_TRACKING_URI
          value: "http://mlflow.default.svc.cluster.local:5000"
        - name: MARKET_DATA_TOPIC
          value: "market-data"
        - name: STRATEGY_SIGNALS_TOPIC
          value: "strategy-signals"
        - name: TRADE_EVENTS_TOPIC
          value: "trade-events"
        - name: ML_MODEL_REGISTRY_URL
          value: "http://mlflow.default.svc.cluster.local:5000"
        - name: FEATURE_STORE_URL
          value: "http://minio.default.svc.cluster.local:9000"
        - name: MINIO_ACCESS_KEY
          value: "admin"
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret-key
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: strategy-engine
  namespace: alphintra-dev
  labels:
    app: strategy-engine
spec:
  selector:
    app: strategy-engine
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: alphintra-dev
type: Opaque
data:
  secret-key: cGFzc3dvcmQxMjM= # password123