apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alphintra
resources:
  - customer-support-service
patches:
  - path: patches/customer-support-deployment.yaml
  - path: patches/customer-support-service-cloudsql.yaml
  - path: patches/customer-support-service-serviceaccount.yaml
  - path: patches/customer-support-configmap.yaml
  - path: patches/customer-support-secret.yaml
images:
  - name: us-central1-docker.pkg.dev/alphintra-472817/alphintra/customer-support-service
    newTag: latest
