apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alphintra
resources:
  - auth-service
  - gateway
patches:
  - path: patches/auth-deployment.yaml
  - path: patches/auth-service-cloudsql.yaml
  - path: patches/auth-service-serviceaccount.yaml
images:
  - name: us-central1-docker.pkg.dev/alphintra-472817/alphintra/auth-service
    newTag: latest
  - name: us-central1-docker.pkg.dev/alphintra-472817/alphintra/service-gateway
    newTag: latest
configMapGenerator:
  - name: auth-service-config
    behavior: merge
    literals:
      - kyc-endpoint=https://dev-kyc.alphintra.internal
      - log-level=DEBUG
      - STRIPE_SUCCESS_URL=https://alphintra.com/subscription/success
      - STRIPE_CANCEL_URL=https://alphintra.com/subscription/cancel
  - name: service-gateway-config
    behavior: merge
    literals:
      - AUTH_SERVICE_URI=http://auth-service.alphintra.svc.cluster.local:8009
      - TRADING_ENGINE_URI=http://trading-engine.alphintra.svc.cluster.local:8100
      - MARKETPLACE_SERVICE_URI=http://marketplace-service.alphintra.svc.cluster.local:8200
      - GRAPHQL_SERVICE_URI=http://graphql-service.alphintra.svc.cluster.local:8300
      - MARKET_DATA_WS_URI=ws://market-data.alphintra.svc.cluster.local:8082
      - GATEWAY_RATE_LIMIT_REPLENISH=30
      - GATEWAY_RATE_LIMIT_BURST=60
      - RISK_MANAGEMENT_URI=http://risk-management-service.alphintra.svc.cluster.local:8002
      - STRATEGY_SERVICE_URI=http://strategy-service.alphintra.svc.cluster.local:8003
      - NO_CODE_SERVICE_URI=http://no-code-service.alphintra.svc.cluster.local:8004
      - AI_ML_SERVICE_URI=http://ai-ml-strategy-service.alphintra.svc.cluster.local:8002
      - CUSTOMER_SUPPORT_SERVICE_URI=http://customer-support-service.alphintra.svc.cluster.local:8010
secretGenerator:
  - name: auth-service-secrets
    behavior: merge
    literals:
      - STRIPE_API_KEY=sk_test_51SJrdmI8b6luJNpeAKKwZyqWcoEsHNuVgyPQ16qY6qtmMHeu18OuiAKx8V68cm9OdtbAAb3EimwYsKaV1nlUiQkr00jEKvOBsC
      - STRIPE_WEBHOOK_SECRET=whsec_q4Y6z8A3SkCIQCUEHwS2CjgmNAtRT6nv
      - STRIPE_PRICE_ID_BASIC=price_1SJsePI8b6luJNpeBVzbXtCJ
      - STRIPE_PRICE_ID_PRO=price_1SJsePI8b6luJNpeBVzbXtCJ
      - STRIPE_PRICE_ID_ENTERPRISE=price_1SJsePI8b6luJNpeBVzbXtCJ
