apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-engine
spec:
  template:
    spec:
      containers:
      # Add Cloud SQL proxy sidecar to trading engine deployment
      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.1
        args:
          - "--port=5432"
          - "--address=127.0.0.1"
          - "--private-ip"
          - "alphintra-472817:us-central1:alphintra-db-instance"
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 50m
            memory: 128Mi
