apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: no-code-service-pdb
  namespace: alphintra
  labels:
    app: no-code-service
    component: backend
    tier: service
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: no-code-service