apiVersion: v1
kind: ServiceAccount
metadata:
  name: no-code-service-sa
  namespace: alphintra
  annotations:
    iam.gke.io/gcp-service-account: no-code-service@alphintra-472817.iam.gserviceaccount.com