server:
  port: 8085
  servlet:
    context-path: /api/support

spring:
  application:
    name: customer-support-service
  
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/alphintra_support
    username: postgres
    password: alphintra123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
  
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: false
        jdbc:
          time_zone: UTC
    show-sql: false
  
  flyway:
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
  
  data:
    redis:
      host: localhost
      port: 6379
      password: 
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:support@alphintra.com}
    password: ${MAIL_PASSWORD:password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8081/auth}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.alphintra.customersupport: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/customer-support-service.log

# Customer Support Service Configuration
support:
  ai:
    enabled: true
    openai:
      api-key: ${OPENAI_API_KEY:sk-test-key}
      model: gpt-4
      max-tokens: 500
      temperature: 0.7
  
  ticket:
    auto-assignment: true
    escalation:
      auto-escalate-after-hours: 24
      max-escalation-level: 3
    sla:
      response-time-minutes:
        low: 480      # 8 hours
        medium: 240   # 4 hours
        high: 60      # 1 hour
        urgent: 15    # 15 minutes
        critical: 5   # 5 minutes
  
  communication:
    websocket:
      enabled: true
      heartbeat-interval: 30000
    email:
      enabled: true
      template-path: classpath:templates/email/
    sms:
      enabled: false
      provider: twilio
  
  knowledge-base:
    elasticsearch:
      enabled: true
      hosts: localhost:9200
      index-name: support-kb
    auto-learning: true
  
  security:
    data-masking:
      enabled: true
      mask-patterns:
        email: "(.{2}).*@"
        phone: "(\\d{3})\\d{4}(\\d{3})"
    consent:
      default-duration-hours: 4
      max-duration-hours: 24
  
  monitoring:
    metrics:
      enabled: true
      export-interval: 60s
    alerts:
      high-priority-tickets: 10
      agent-overload-threshold: 0.9

---
spring:
  config:
    activate:
      on-profile: kubernetes
  
  datasource:
    url: jdbc:postgresql://postgresql-service:5432/alphintra_support
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:alphintra123}
  
  data:
    redis:
      host: redis-service
      port: 6379
      password: ${REDIS_PASSWORD:}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

support:
  knowledge-base:
    elasticsearch:
      hosts: elasticsearch-service:9200

---
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://postgres:5432/alphintra_support
    username: postgres
    password: alphintra123
  
  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/