apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-ml-strategy-config
  namespace: alphintra
  labels:
    app: ai-ml-strategy-service
    component: configuration
data:
  # Google Cloud Platform Configuration
  gcp-project-id: "alphintra-prod"
  gcp-region: "us-central1"
  gcs-bucket-name: "alphintra-ai-ml-data"
  vertex-ai-location: "us-central1"
  
  # MLflow Configuration
  mlflow-tracking-uri: "http://mlflow-service:5000"
  mlflow-experiment-name: "alphintra-strategies"
  
  # Kafka Configuration
  kafka-bootstrap-servers: "kafka-service:9092"
  kafka-consumer-group: "ai-ml-strategy-service"
  
  # Service URLs
  auth-service-url: "http://auth-service:8080"
  trading-engine-url: "http://trading-engine:8080"
  market-data-service-url: "http://market-data-service:8080"
  
  # Application Configuration
  log-level: "INFO"
  max-dataset-size-mb: "1024"
  max-training-time-hours: "24"
  max-backtest-years: "10"
  
  # Rate Limiting
  rate-limit-per-minute: "100"
  rate-limit-burst: "200"
  
  # CORS Configuration
  allowed-origins: "https://trading.alphintra.com,https://api.alphintra.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-ml-strategy-db-secret
  namespace: alphintra
  labels:
    app: ai-ml-strategy-service
    component: database
type: Opaque
stringData:
  database-url: "postgresql+asyncpg://ai_ml_user:REPLACE_WITH_PASSWORD@postgres-service:5432/ai_ml_strategy_db"
  timescale-database-url: "postgresql+asyncpg://ai_ml_user:REPLACE_WITH_PASSWORD@timescaledb-service:5432/ai_ml_timeseries_db"

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-ml-strategy-redis-secret
  namespace: alphintra
  labels:
    app: ai-ml-strategy-service
    component: cache
type: Opaque
stringData:
  redis-url: "redis://redis-service:6379/2"

---
apiVersion: v1
kind: Secret
metadata:
  name: ai-ml-strategy-auth-secret
  namespace: alphintra
  labels:
    app: ai-ml-strategy-service
    component: authentication
type: Opaque
stringData:
  secret-key: "REPLACE_WITH_RANDOM_SECRET_KEY_FOR_JWT_SIGNING"