apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: service-gateway
  labels:
    app: service-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: service-gateway
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
