apiVersion: v1
kind: Service
metadata:
  name: marketplace-service
  labels:
    app: marketplace-service
    component: backend
    environment: dev
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8200"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8200
      targetPort: http
      protocol: TCP
  selector:
    app: marketplace-service
