spring:
  application:
    name: service-gateway
  main:
    web-application-type: reactive
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 2000ms
  cloud:
    gateway:
      # Global CORS for browser clients
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${GATEWAY_CORS_ALLOWED_ORIGINS:*}
            allowedMethods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
            allowedHeaders: "*"
            exposedHeaders: "X-Correlation-Id,X-RateLimit-Remaining,X-RateLimit-Replenish-Rate,X-RateLimit-Burst-Capacity"
            allowCredentials: false
      httpclient:
        connect-timeout: 4000
        response-timeout: 60000
      default-filters:
        - name: RequestSize
          args:
            maxSize: ${GATEWAY_MAX_REQUEST_SIZE:10MB}
        - name: Retry
          args:
            retries: 2
            statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE,GATEWAY_TIMEOUT
        - name: CircuitBreaker
          args:
            name: globalCircuitBreaker
            fallbackUri: forward:/_fallback/unavailable
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URI:http://auth-service.default.svc.cluster.local:8009}
          predicates:
            - Path=/api/auth/**, /api/users/**, /api/kyc/**, /api/subscriptions/**
          filters:
            - PreserveHostHeader
            # - RemoveRequestHeader=Cookie  # Commented out to allow JWT tokens to pass through
        - id: trading-engine
          uri: ${TRADING_ENGINE_URI:http://trading-engine.default.svc.cluster.local:8008}
          predicates:
            - Path=/api/trading/**, /api/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
        - id: marketplace-service
          uri: ${MARKETPLACE_SERVICE_URI:http://marketplace-service.default.svc.cluster.local:8200}
          predicates:
            - Path=/api/marketplace/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
        - id: graphql-service
          uri: ${GRAPHQL_SERVICE_URI:http://graphql-service.default.svc.cluster.local:8300}
          predicates:
            - Path=/graphql/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
        - id: market-data-websocket
          uri: ${MARKET_DATA_WS_URI:ws://market-data.default.svc.cluster.local:8082}
          predicates:
            - Path=/ws/market/**
          filters:
            - PreserveHostHeader
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
        - id: risk-management-service
          uri: ${RISK_MANAGEMENT_URI:http://risk-management-service.platform:8002}
          predicates:
            - Path=/api/risk-profiles/**, /api/portfolio/**, /api/positions/**, /api/trades/**, /api/stress-tests/**, /api/reports/**, /api/emergency/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
        - id: strategy-service
          uri: ${STRATEGY_SERVICE_URI:http://strategy-service.platform:8003}
          predicates:
            - Path=/api/strategies/**, /api/backtests/**, /api/live-trading/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
        - id: no-code-service
          uri: ${NO_CODE_SERVICE_URI:http://no-code-service.platform:8004}
          predicates:
            - Path=/api/workflows/**, /api/executions/**, /api/components/**, /api/templates/**, /api/workflow-versions/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
        - id: ai-ml-strategy-service
          uri: ${AI_ML_SERVICE_URI:http://ai-ml-strategy-service.platform:8002}
          predicates:
            - Path=/api/files/**, /api/ai/**, /feature-engineering
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
        - id: customer-support-service
          uri: ${CUSTOMER_SUPPORT_SERVICE_URI:http://customer-support-service.platform:8010}
          predicates:
            - Path=/api/customer-support/**, /ws/support/**, /ws/tickets/**
          filters:
            - PreserveHostHeader
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
        - id: wallet-service
          uri: ${WALLET_SERVICE_URI:http://wallet-service.alphintra.svc.cluster.local:8011}
          predicates:
            - Path=/binance/**, /coinbase/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: ${GATEWAY_RATE_LIMIT_REPLENISH:40}
                redis-rate-limiter.burstCapacity: ${GATEWAY_RATE_LIMIT_BURST:80}
                key-resolver: "#{@principalKeyResolver}"
server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    com.alphintra.gateway: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
  health:
    redis:
      enabled: false

# JWT validation is removed; no gateway.security config is used.
