apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  labels:
    app: auth-service
data:
  kyc-endpoint: https://kyc-placeholder.example.com
  log-level: INFO
  # Stripe Redirect URLs for Production - Moved to dev folder
  # STRIPE_SUCCESS_URL: https://alphintra.com/subscription/success
  # STRIPE_CANCEL_URL: https://alphintra.com/subscription/cancel
