apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-service
      containers:
        - name: auth-service
          image: gcr.io/alphintra-472817/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8009
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: SERVER_PORT
              value: "8009"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_NAME
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: JWT_SECRET
            - name: KYC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: KYC_API_KEY
                  optional: true
            - name: KYC_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: kyc-endpoint
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 250m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8009
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8009
            initialDelaySeconds: 30
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8009
            failureThreshold: 30
            periodSeconds: 10
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 2000
