apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      serviceAccountName: auth-service
      containers:
        - name: auth-service
          image: us-central1-docker.pkg.dev/alphintra-472817/alphintra/auth-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8009
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: SERVER_PORT
              value: "8009"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: db-host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: db-port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: db-name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: db-password
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: jwt-secret
            - name: KYC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: auth-service-secrets
                  key: kyc-api-key
            - name: KYC_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: auth-service-config
                  key: kyc-endpoint
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8009
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8009
            initialDelaySeconds: 30
            periodSeconds: 30
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8009
            failureThreshold: 10
            periodSeconds: 10
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
