apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  labels:
    app: auth-service
type: Opaque
stringData:
  DB_HOST: "replace-with-cloudsql-connection"
  DB_PORT: "5432"
  DB_NAME: "alphintra_auth_service"
  DB_USERNAME: "alphintra"
  DB_PASSWORD: "replace-with-db-password"
  JWT_SECRET: "replace-with-jwt-secret"
