apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  labels:
    app: auth-service
type: Opaque
stringData:
  DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  DB_NAME: "alphintra_auth_service"
  DB_USERNAME: "alphintra"
  DB_PASSWORD: "AlphaTemp!2024"
  JWT_SECRET: "U29tZVZlcnlTdHJvbmdTZWNyZXRLZXlXaXRoRW5vdWdoQnl0ZXNGb3JFUjUxMkFsZ29yaXRobS0xMjM0NTY3ODkwYWJjZGVmZ2hpams="
