apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-code-service
spec:
  template:
    spec:
      containers:
      - name: no-code-service
        env:
        # Production optimizations
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: PYTHONDONTWRITEBYTECODE
          value: "1"
        # Resource optimizations
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1.5Gi"
            cpu: "750m"
        # Enhanced health checks
        livenessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8006
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
