apiVersion: v1
kind: Service
metadata:
  name: no-code-service
  annotations:
    # Prometheus monitoring
    prometheus.io/scrape: "true"
    prometheus.io/port: "8006"
    prometheus.io/path: "/metrics"