import { Strategy } from './types';

const mockStrategies: Strategy[] = [
 {
    id: '1',
    name: 'Bitcoin devil',
    creatorId: 'creator1',
    creatorName: 'Amar',
    description: 'Bull rider',
    category: 'Momentum',
    assetType: 'Cryptocurrency',
    tradingPairs: ['BTC/USDT', 'ETH/USDT'],
    price: 99.99,
    pricingModel: 'SUBSCRIPTION',
    revenueSharePercentage: 30,
    riskLevel: 'medium',
    verificationStatus: 'APPROVED',
    performance: {
      totalReturn: 152.3,
      annualizedReturn: 85.6,
      maxDrawdown: -10.2,
      sharpeRatio: 2.4,
      winRate: 68.5,
    },
    rating: 5,
    reviewCount: 2,
    subscriberCount: 342,
    lastUpdated: '2025-08-15',
    isVerified: true,
    thumbnail: 'bull-rider',
    gradientColors: ['#1e3a8a', '#3b82f6', '#60a5fa'],
  },
  {
    id: '2',
    name: 'Bitcoin devil',
    creatorId: 'creator2',
    creatorName: 'Sophia',
    description: 'Bear trader',
    category: 'Arbitrage',
    assetType: 'Cryptocurrency',
    tradingPairs: ['BTC/USDT', 'LTC/USDT'],
    price: 149,
    pricingModel: 'ONE_TIME',
    revenueSharePercentage: 20,
    riskLevel: 'low',
    verificationStatus: 'PENDING',
    performance: {
      totalReturn: 78.9,
      annualizedReturn: 35.2,
      maxDrawdown: -3.4,
      sharpeRatio: 1.8,
      winRate: 74.1,
    },
    rating: 4.3,
    reviewCount: 95,
    subscriberCount: 158,
    lastUpdated: '2025-07-20',
    isVerified: false,
    thumbnail: 'bear-trader',
    gradientColors: ['#7c2d12', '#dc2626', '#ef4444'],
  },
  {
    id: '3',
    name: 'WOLF AI',
    creatorId: 'creator3',
    creatorName: 'Ravi',
    description: 'Computational Biology - WOLF AI',
    category: 'Quantitative',
    assetType: 'Equities',
    tradingPairs: ['AAPL/USD', 'TSLA/USD'],
    price: 199,
    pricingModel: 'SUBSCRIPTION',
    revenueSharePercentage: 40,
    riskLevel: 'high',
    verificationStatus: 'APPROVED',
    performance: {
      totalReturn: 245.6,
      annualizedReturn: 112.4,
      maxDrawdown: -18.7,
      sharpeRatio: 3.1,
      winRate: 61.3,
    },
    rating: 4.9,
    reviewCount: 276,
    subscriberCount: 487,
    lastUpdated: '2025-08-25',
    isVerified: true,
    thumbnail: 'market-reversal',
    gradientColors: ['#831843', '#db2777', '#ec4899'],
  },
  {
    id: '4',
    name: 'WOLF AI',
    creatorId: 'creator4',
    creatorName: 'Emma',
    description: 'AI Computational Biology - WOLF AI',
    category: 'AI Trading',
    assetType: 'Cryptocurrency',
    tradingPairs: ['ETH/USDT', 'SOL/USDT'],
    price: 299,
    pricingModel: 'SUBSCRIPTION',
    revenueSharePercentage: 35,
    riskLevel: 'high',
    verificationStatus: 'APPROVED',
    performance: {
      totalReturn: 312.4,
      annualizedReturn: 145.8,
      maxDrawdown: -15.3,
      sharpeRatio: 2.9,
      winRate: 65.7,
    },
    rating: 4.8,
    reviewCount: 234,
    subscriberCount: 521,
    lastUpdated: '2025-08-28',
    isVerified: true,
    thumbnail: 'ai-confirmation',
    gradientColors: ['#065f46', '#10b981', '#34d399'],
  },
  {
    id: '5',
    name: 'Dip Raider',
    creatorId: 'creator5',
    creatorName: 'Marcus',
    description: 'Pullback Warrior Strategy - Bynik',
    category: 'Mean Reversion',
    assetType: 'Cryptocurrency',
    tradingPairs: ['BTC/USDT', 'ETH/USDT', 'BNB/USDT'],
    price: 79,
    pricingModel: 'SUBSCRIPTION',
    revenueSharePercentage: 25,
    riskLevel: 'medium',
    verificationStatus: 'APPROVED',
    performance: {
      totalReturn: 189.7,
      annualizedReturn: 92.3,
      maxDrawdown: -12.8,
      sharpeRatio: 2.2,
      winRate: 70.4,
    },
    rating: 4.6,
    reviewCount: 167,
    subscriberCount: 398,
    lastUpdated: '2025-08-20',
    isVerified: true,
    thumbnail: 'dip-raider',
    gradientColors: ['#581c87', '#a855f7', '#c084fc'],
  },
  {
    id: '6',
    name: 'Apex AI Trend 5 min',
    creatorId: 'creator6',
    creatorName: 'Sarah',
    description: 'High-frequency trend following - Ryze',
    category: 'Trend Following',
    assetType: 'Cryptocurrency',
    tradingPairs: ['BTC/USDT', 'ETH/USDT'],
    price: 129,
    pricingModel: 'SUBSCRIPTION',
    revenueSharePercentage: 30,
    riskLevel: 'high',
    verificationStatus: 'APPROVED',
    performance: {
      totalReturn: 278.3,
      annualizedReturn: 128.5,
      maxDrawdown: -16.9,
      sharpeRatio: 2.7,
      winRate: 63.2,
    },
    rating: 4.7,
    reviewCount: 203,
    subscriberCount: 445,
    lastUpdated: '2025-08-29',
    isVerified: true,
    thumbnail: 'apex-5min',
    gradientColors: ['#1e40af', '#3b82f6', '#60a5fa'],
  },
  {
    id: '7',
    name: 'Apex AI Trend 4 hours',
    creatorId: 'creator7',
    creatorName: 'David',
    description: 'Medium-term trend strategy - Ryze',
    category: 'Trend Following',
    assetType: 'Cryptocurrency',
    tradingPairs: ['BTC/USDT', 'ETH/USDT'],
    price: 149,
    pricingModel: 'SUBSCRIPTION',
    revenueSharePercentage: 30,
    riskLevel: 'medium',
    verificationStatus: 'APPROVED',
    performance: {
      totalReturn: 195.8,
      annualizedReturn: 98.7,
      maxDrawdown: -11.3,
      sharpeRatio: 2.5,
      winRate: 69.8,
    },
    rating: 4.8,
    reviewCount: 221,
    subscriberCount: 512,
    lastUpdated: '2025-08-30',
    isVerified: true,
    thumbnail: 'apex-4h',
    gradientColors: ['#1e40af', '#3b82f6', '#60a5fa'],
  },
  {
    id: '8',
    name: 'Apex AI Trend 1 minute',
    creatorId: 'creator8',
    creatorName: 'Lisa',
    description: 'Ultra high-frequency scalping - Ryze',
    category: 'Scalping',
    assetType: 'Cryptocurrency',
    tradingPairs: ['BTC/USDT', 'ETH/USDT'],
    price: 179,
    pricingModel: 'SUBSCRIPTION',
    revenueSharePercentage: 35,
    riskLevel: 'high',
    verificationStatus: 'APPROVED',
    performance: {
      totalReturn: 298.4,
      annualizedReturn: 142.6,
      maxDrawdown: -19.2,
      sharpeRatio: 2.6,
      winRate: 61.9,
    },
    rating: 4.6,
    reviewCount: 189,
    subscriberCount: 456,
    lastUpdated: '2025-08-31',
    isVerified: true,
    thumbnail: 'apex-1min',
    gradientColors: ['#1e40af', '#3b82f6', '#60a5fa'],
  },
];

export default mockStrategies;
