import { Strategy } from './types';

const mockStrategies: Strategy[] = [
  {
    "id": "1",
    "name": "Crypto Momentum Booster",
    "creatorId": "dev1",
    "creatorName": "Alex Trader",
    "description": "High-momentum strategy for crypto assets",
    "category": "Momentum",
    "assetType": "Cryptocurrency",
    "tradingPairs": ["BTC/USDT", "ETH/USDT"],
    "price": "free",
    "riskLevel": "high",
    "verificationStatus": "APPROVED",
    "performance": {
      "totalReturn": 180.5,
      "annualizedReturn": 95.2,
      "maxDrawdown": -15.8,
      "sharpeRatio": 2.8,
      "winRate": 72.3
    },
    "rating": 4.7,
    "reviewCount": 150,
    "subscriberCount": 500,
    "lastUpdated": "2025-10-16",
    "isVerified": true,
    "thumbnail": "bull-rider",
    "gradientColors": ["#1e3a8a", "#3b82f6", "#60a5fa"]
  },
  {
    "id": "2",
    "name": "Equity Mean Reversion",
    "creatorId": "dev2",
    "creatorName": "Bella Investor",
    "description": "Mean reversion for stock markets",
    "category": "Mean Reversion",
    "assetType": "Equities",
    "tradingPairs": ["AAPL/USD", "MSFT/USD"],
    "price": 49.99,
    "riskLevel": "low",
    "verificationStatus": "PENDING",
    "performance": {
      "totalReturn": 65.4,
      "annualizedReturn": 30.1,
      "maxDrawdown": -5.6,
      "sharpeRatio": 1.5,
      "winRate": 78.9
    },
    "rating": 4.2,
    "reviewCount": 80,
    "subscriberCount": 200,
    "lastUpdated": "2025-09-01",
    "isVerified": false,
    "thumbnail": "bear-trader",
    "gradientColors": ["#7c2d12", "#dc2626", "#ef4444"]
  },
  {
    "id": "3",
    "name": "AI Crypto Arbitrage",
    "creatorId": "dev3",
    "creatorName": "Charlie AI",
    "description": "AI-driven arbitrage in crypto",
    "category": "Arbitrage",
    "assetType": "Cryptocurrency",
    "tradingPairs": ["BTC/USDT", "LTC/USDT"],
    "price": 99,
    "riskLevel": "medium",
    "verificationStatus": "APPROVED",
    "performance": {
      "totalReturn": 120.8,
      "annualizedReturn": 60.4,
      "maxDrawdown": -8.9,
      "sharpeRatio": 2.1,
      "winRate": 65.7
    },
    "rating": 4.9,
    "reviewCount": 300,
    "subscriberCount": 800,
    "lastUpdated": "2025-10-10",
    "isVerified": true,
    "thumbnail": "market-reversal",
    "gradientColors": ["#831843", "#db2777", "#ec4899"]
  },
  {
    "id": "4",
    "name": "Stock Trend Follower",
    "creatorId": "dev4",
    "creatorName": "Dana Stocks",
    "description": "Trend following for equities",
    "category": "Trend Following",
    "assetType": "Equities",
    "tradingPairs": ["GOOGL/USD", "AMZN/USD"],
    "price": "free",
    "riskLevel": "high",
    "verificationStatus": "REJECTED",
    "performance": {
      "totalReturn": 210.2,
      "annualizedReturn": 105.1,
      "maxDrawdown": -20.3,
      "sharpeRatio": 3.0,
      "winRate": 55.4
    },
    "rating": 3.8,
    "reviewCount": 50,
    "subscriberCount": 100,
    "lastUpdated": "2025-08-05",
    "isVerified": false,
    "thumbnail": "ai-confirmation",
    "gradientColors": ["#065f46", "#10b981", "#34d399"]
  },
  {
    "id": "5",
    "name": "Crypto Scalper Pro",
    "creatorId": "dev5",
    "creatorName": "Evan Scalp",
    "description": "High-frequency scalping in crypto",
    "category": "Scalping",
    "assetType": "Cryptocurrency",
    "tradingPairs": ["ETH/USDT", "BNB/USDT"],
    "price": 79.99,
    "riskLevel": "high",
    "verificationStatus": "APPROVED",
    "performance": {
      "totalReturn": 300.1,
      "annualizedReturn": 150.0,
      "maxDrawdown": -25.4,
      "sharpeRatio": 2.6,
      "winRate": 60.2
    },
    "rating": 4.5,
    "reviewCount": 200,
    "subscriberCount": 600,
    "lastUpdated": "2025-10-17",
    "isVerified": true,
    "thumbnail": "dip-raider",
    "gradientColors": ["#581c87", "#a855f7", "#c084fc"]
  },
  {
    "id": "6",
    "name": "Quantitative Equity Model",
    "creatorId": "dev6",
    "creatorName": "Fiona Quant",
    "description": "Quantitative analysis for stocks",
    "category": "Quantitative",
    "assetType": "Equities",
    "tradingPairs": ["TSLA/USD", "NVDA/USD"],
    "price": 150,
    "riskLevel": "medium",
    "verificationStatus": "PENDING",
    "performance": {
      "totalReturn": 140.7,
      "annualizedReturn": 70.3,
      "maxDrawdown": -12.1,
      "sharpeRatio": 2.2,
      "winRate": 68.8
    },
    "rating": 4.4,
    "reviewCount": 120,
    "subscriberCount": 350,
    "lastUpdated": "2025-09-15",
    "isVerified": false,
    "thumbnail": "apex-5min",
    "gradientColors": ["#1e40af", "#3b82f6", "#60a5fa"]
  },
  {
    "id": "7",
    "name": "AI Trading Bot",
    "creatorId": "dev7",
    "creatorName": "George AI",
    "description": "AI-powered trading decisions",
    "category": "AI Trading",
    "assetType": "Cryptocurrency",
    "tradingPairs": ["SOL/USDT", "ADA/USDT"],
    "price": "free",
    "riskLevel": "low",
    "verificationStatus": "APPROVED",
    "performance": {
      "totalReturn": 90.5,
      "annualizedReturn": 45.2,
      "maxDrawdown": -4.5,
      "sharpeRatio": 1.9,
      "winRate": 75.6
    },
    "rating": 4.8,
    "reviewCount": 250,
    "subscriberCount": 700,
    "lastUpdated": "2025-10-12",
    "isVerified": true,
    "thumbnail": "apex-4h",
    "gradientColors": ["#1e40af", "#3b82f6", "#60a5fa"]
  },
  {
    "id": "8",
    "name": "Balanced Portfolio Strategy",
    "creatorId": "dev8",
    "creatorName": "Hannah Balance",
    "description": "Balanced approach for mixed assets",
    "category": "Mean Reversion",
    "assetType": "Equities",
    "tradingPairs": ["AAPL/USD", "GOOGL/USD"],
    "price": 29.99,
    "riskLevel": "low",
    "verificationStatus": "REJECTED",
    "performance": {
      "totalReturn": 50.3,
      "annualizedReturn": 25.1,
      "maxDrawdown": -3.2,
      "sharpeRatio": 1.4,
      "winRate": 80.1
    },
    "rating": 3.9,
    "reviewCount": 60,
    "subscriberCount": 150,
    "lastUpdated": "2025-07-01",
    "isVerified": false,
    "thumbnail": "apex-1min",
    "gradientColors": ["#1e40af", "#3b82f6", "#60a5fa"]
  },
  {
    "id": "9",
    "name": "High Yield Crypto",
    "creatorId": "dev9",
    "creatorName": "Ian Yield",
    "description": "Focus on high yield crypto trades",
    "category": "Scalping",
    "assetType": "Cryptocurrency",
    "tradingPairs": ["XRP/USDT", "DOGE/USDT"],
    "price": 199.99,
    "riskLevel": "high",
    "verificationStatus": "APPROVED",
    "performance": {
      "totalReturn": 250.9,
      "annualizedReturn": 125.4,
      "maxDrawdown": -22.7,
      "sharpeRatio": 2.9,
      "winRate": 58.5
    },
    "rating": 4.6,
    "reviewCount": 180,
    "subscriberCount": 450,
    "lastUpdated": "2025-10-15",
    "isVerified": true,
    "thumbnail": "bull-rider",
    "gradientColors": ["#1e3a8a", "#3b82f6", "#60a5fa"]
  },
  {
    "id": "10",
    "name": "Stable Stock Investor",
    "creatorId": "dev10",
    "creatorName": "Jenna Stable",
    "description": "Stable long-term stock investments",
    "category": "Trend Following",
    "assetType": "Equities",
    "tradingPairs": ["MSFT/USD", "AMZN/USD"],
    "price": 99,
    "riskLevel": "medium",
    "verificationStatus": "PENDING",
    "performance": {
      "totalReturn": 110.6,
      "annualizedReturn": 55.3,
      "maxDrawdown": -9.8,
      "sharpeRatio": 2.0,
      "winRate": 70.0
    },
    "rating": 4.3,
    "reviewCount": 100,
    "subscriberCount": 300,
    "lastUpdated": "2025-06-20",
    "isVerified": false,
    "thumbnail": "bear-trader",
    "gradientColors": ["#7c2d12", "#dc2626", "#ef4444"]
  }
];

export default mockStrategies;