apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "2"
    spec:
      containers:
        - name: auth-service
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: KYC_ENDPOINT
              value: https://staging-kyc.alphintra.internal
            - name: LOG_LEVEL
              value: INFO
