apiVersion: v1
kind: Namespace
metadata:
  name: alphintra-production
  labels:
    name: alphintra-production
    environment: production
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
  annotations:
    kubernetes.io/managed-by: "argocd"
    argocd.argoproj.io/sync-wave: "-1"
---
# Resource quota for production namespace
apiVersion: v1
kind: ResourceQuota
metadata:
  name: alphintra-production-quota
  namespace: alphintra-production
  labels:
    environment: production
spec:
  hard:
    # Compute resources
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi
    
    # Storage resources
    requests.storage: 100Gi
    persistentvolumeclaims: "10"
    
    # Object count quotas
    pods: "50"
    services: "20"
    secrets: "20"
    configmaps: "20"
    replicationcontrollers: "0"
    
    # Network policies
    count/networkpolicies.networking.k8s.io: "10"
---
# Limit range for production namespace
apiVersion: v1
kind: LimitRange
metadata:
  name: alphintra-production-limits
  namespace: alphintra-production
  labels:
    environment: production
spec:
  limits:
    # Default limits for containers
    - default:
        cpu: 500m
        memory: 1Gi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
      type: Container
    
    # Limits for persistent volume claims
    - default:
        storage: 10Gi
      type: PersistentVolumeClaim
    
    # Pod limits
    - max:
        cpu: "4"
        memory: 8Gi
      type: Pod