apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: service-gateway
  namespace: gateway
spec:
  host: service-gateway
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    connectionPool:
      http:
        http1MaxPendingRequests: 1000
        maxRequestsPerConnection: 100
  subsets:
    - name: stable
      labels:
        version: stable
    - name: canary
      labels:
        version: canary
