apiVersion: v1
kind: Secret
metadata:
  name: customer-support-service-secrets
  namespace: alphintra
type: Opaque
data:
  # Base64 encoded values - these will be overwritten by patches
  database-url: ""
  db-user: ""
  db-password: ""
  jwt-secret: ""