# Cloud Build Local specific optimizations
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api-gateway
        resources:
          requests:
            memory: "200Mi"
            cpu: "150m"
          limits:
            memory: "400Mi"
            cpu: "300m"
        # Distroless-optimized health checks
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: auth-service
        resources:
          requests:
            memory: "100Mi"
            cpu: "100m"
          limits:
            memory: "200Mi"
            cpu: "200m"
        # Distroless-optimized health checks
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
        startupProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 30

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-service
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: trading-service
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: graphql-gateway
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-engine
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: strategy-engine
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "250m"
