# Resource Optimization Patches for Production-Ready Deployment
# Memory and CPU right-sizing for all services

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: api-gateway
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        env:
        - name: JAVA_OPTS
          value: "-server -Xmx256m -Xms128m -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -Djava.security.egd=file:/dev/./urandom -Dspring.backgroundpreinitializer.ignore=true -Dspring.jmx.enabled=false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: auth-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: JAVA_OPTS
          value: "-server -Xmx128m -Xms64m -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -Djava.security.egd=file:/dev/./urandom -Dspring.backgroundpreinitializer.ignore=true -Dspring.jmx.enabled=false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: eureka-server
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: JAVA_OPTS
          value: "-server -Xmx128m -Xms64m -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -Djava.security.egd=file:/dev/./urandom -Dspring.backgroundpreinitializer.ignore=true -Dspring.jmx.enabled=false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: config-server
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: JAVA_OPTS
          value: "-server -Xmx128m -Xms64m -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCompressedClassPointers -Djava.security.egd=file:/dev/./urandom -Dspring.backgroundpreinitializer.ignore=true -Dspring.jmx.enabled=false"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-service
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: trading-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: graphql-gateway
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-engine
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: strategy-engine
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: broker-simulator
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: broker-simulator
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-code-service
  namespace: alphintra
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: no-code-service
        resources:
          requests:
            memory: "256Mi"
            cpu: "150m"
          limits:
            memory: "512Mi"
            cpu: "300m"