apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The 'infra' directory is now at the root of the workspace.
# The path to the base manifests is relative to this kustomization file.
resources:
  - gateway

patches:
  - path: patches/gateway-deployment.yaml
  - path: patches/gateway-hpa.yaml