apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the wallet-service subdirectory directly
resources:
  - wallet-service

# Apply environment-specific patches
patches:
  - path: patches/wallet-service-cloudsql.yaml
    target:
      kind: Deployment
      name: wallet-service

namespace: alphintra

commonLabels:
  app: wallet-service
  version: v1
  component: backend
  environment: dev

replicas:
  - name: wallet-service
    count: 1

images:
  - name: gcr.io/alphintra-472817/wallet-service
    newTag: latest