apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-api
  labels:
    app: trading-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-api
  template:
    metadata:
      labels:
        app: trading-api
    spec:
      containers:
      - name: trading-api
        image: trading-api:simple
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        # Simplified version - no external dependencies

---

apiVersion: v1
kind: Service
metadata:
  name: trading-api-service
spec:
  selector:
    app: trading-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort