apiVersion: apps/v1
kind: Deployment
metadata:
  name: alphintra-frontend
  namespace: default
  labels:
    app: alphintra-frontend
    environment: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alphintra-frontend
  template:
    metadata:
      labels:
        app: alphintra-frontend
        environment: dev
    spec:
      containers:
      - name: alphintra-frontend
        image: gcr.io/PROJECT_ID/alphintra-frontend:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: NEXT_PUBLIC_APP_URL
          value: "https://alphintra.dev"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.alphintra.dev"
        - name: NEXT_PUBLIC_WS_URL
          value: "wss://api.alphintra.dev"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
      securityContext:
        fsGroup: 1001