apiVersion: v1
kind: Service
metadata:
  name: trading-engine
  namespace: alphintra
  labels:
    app: trading-engine
    component: backend
    environment: dev
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8008
    targetPort: http
    protocol: TCP
  selector:
    app: trading-engine