apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: auth-service
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: cloud
            - name: KYC_ENDPOINT
              valueFrom: null
              value: https://dev-kyc.alphintra.internal
            - name: LOG_LEVEL
              value: DEBUG
