server:
  port: 8080
  shutdown: graceful

spring:
  application:
    name: api-gateway
  
  profiles:
    active: local
  
  cloud:
    config:
      enabled: false
    
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials,Access-Control-Allow-Origin
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
      
      discovery:
        locator:
          enabled: false
      
      httpclient:
        connect-timeout: 5000
        response-timeout: 30s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      
      routes:
        # Health check route
        - id: health-check
          uri: http://httpbin.org
          predicates:
            - Path=/health
          filters:
            - SetPath=/status/200
            - AddResponseHeader=X-Gateway-Status, healthy
            
        # Test route for gateway functionality
        - id: test-route
          uri: http://httpbin.org
          predicates:
            - Path=/test/**
          filters:
            - StripPrefix=1
            - SetPath=/anything
            - AddRequestHeader=X-Request-Source, gateway

        # Trading API route
        - id: trading-api-route
          uri: http://localhost:8000
          predicates:
            - Path=/trading/**
          filters:
            - StripPrefix=1
      
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"