name: Deploy no-code-service to GKE using Cloud Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/backend/no-code-service/**'
      - 'infra/kubernetes/overlays/dev/**'
      - '.github/workflows/cd-dev-no-code-service.yml'
  workflow_dispatch:

env:
  GCP_PROJECT_ID: alphintra-472817
  GKE_CLUSTER: alphintra-cluster
  GKE_ZONE: us-central1-a
  SERVICE_NAME: no-code-service

jobs:
  deploy:
    name: Build and deploy using Cloud Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Submit build to Cloud Build
        run: |
          gcloud builds submit \
            --config=src/backend/no-code-service/cloudbuild.yaml \
            --project=$GCP_PROJECT_ID \
            --substitutions=PROJECT_ID=$GCP_PROJECT_ID,COMMIT_SHA=$GITHUB_SHA \
            .

      - name: Verify deployment status
        run: |
          echo "Cloud Build completed. Checking deployment status..."
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT_ID
          kubectl get deployment $SERVICE_NAME -n alphintra -o wide
          kubectl get pods -l app=$SERVICE_NAME -n alphintra