name: Deploy service-gateway to Dev

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID || 'alphintra-472817' }}
  GKE_CLUSTER: alphintra-cluster
  GKE_ZONE: us-central1-a
  SERVICE_NAME: service-gateway

jobs:
  deploy:
    name: Build and deploy service-gateway
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure project
        run: gcloud config set project $GCP_PROJECT_ID

      - name: Submit build to Cloud Build
        run: |
          gcloud builds submit \
            --config=src/backend/service-gateway/cloudbuild.yaml \
            --project=$GCP_PROJECT_ID \
            --substitutions=_COMMIT_SHA=$GITHUB_SHA,_SERVICE_NAME=$SERVICE_NAME

      - name: Configure kubectl
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GCP_PROJECT_ID

      - name: Deploy manifests
        run: |
          kubectl apply -k infra/kubernetes/environments/dev

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/service-gateway -n alphintra --timeout=180s
          kubectl get pods -l app=service-gateway -n alphintra
