name: Deploy no-code-service to GKE using Cloud Build

on:
  push:
    branches: [ main ]
    paths:
      - 'src/backend/no-code-service/**'
      - 'infra/kubernetes/overlays/dev/**'
      - '.github/workflows/cd-dev-no-code-service.yml'
  workflow_dispatch:

env:
  PROJECT_ID: alphintra-472817   # match Cloud SQL instance project
  GKE_CLUSTER: alphintra-cluster
  GKE_ZONE: us-central1-a
  SERVICE_NAME: no-code-service

jobs:
  deploy:
    name: Build and deploy using Cloud Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Prefer Workload Identity Federation; fall back to JSON key if provided
      - name: Authenticate to Google Cloud (WIF)
        if: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER != '' && secrets.GCP_SERVICE_ACCOUNT_EMAIL != '' }}
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Authenticate to Google Cloud (JSON key fallback)
        if: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER == '' || secrets.GCP_SERVICE_ACCOUNT_EMAIL == '' }}
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Fail if no auth credentials are configured
        if: ${{ (secrets.GCP_WORKLOAD_IDENTITY_PROVIDER == '' || secrets.GCP_SERVICE_ACCOUNT_EMAIL == '') && secrets.GCP_SA_KEY == '' }}
        run: |
          echo "Missing authentication configuration. Provide either:" >&2
          echo "- GCP_WORKLOAD_IDENTITY_PROVIDER and GCP_SERVICE_ACCOUNT_EMAIL secrets (recommended), or" >&2
          echo "- GCP_SA_KEY secret with a service account JSON key." >&2
          exit 1

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Submit build to Cloud Build
        run: |
          gcloud builds submit \
            --config=src/backend/no-code-service/cloudbuild.yaml \
            --project=$PROJECT_ID \
            --substitutions=COMMIT_SHA=$GITHUB_SHA \
            .

      - name: Verify deployment status
        run: |
          echo "Cloud Build completed. Checking deployment status..."
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $PROJECT_ID
          kubectl get deployment $SERVICE_NAME -n alphintra -o wide
          kubectl get pods -l app=$SERVICE_NAME -n alphintra